package com.sap.olingo.jpa.processor.core.testmodel;

public interface TestDataConstants {
  int NO_ATTRIBUTES_CHANGE_INFO = 2;
  int NO_ATTRIBUTES_PERSON = 2;
  int NO_ATTRIBUTES_COMMUNICATION_DATA = 4;
  int NO_ATTRIBUTES_BUSINESS_PARTNER = 6;
  int NO_ATTRIBUTES_ORGANIZATION = 4;
  int NO_ATTRIBUTES_POSTAL_ADDRESS = 9;
  int NO_DEC_ATTRIBUTES_BUSINESS_PARTNER = 9;
  int NO_ENTITY_TYPES = 20;
  int NO_ENTITY_SETS = 21;
  int NO_COMPLEXTYPES = 18;

}